### PR TITLE
Fix #420

### LINKED ISSUE #420: TestPipelineCall fails
```
=== RUN   TestPipelineCall
Error:     server_test.go:272: GetNumber() #1 = 1; want 0
Error:     server_test.go:278: GetNumber() #2 = 0; want 1
```

This is new, isn't it? ☝️

_Originally posted by @lthibault in https://github.com/capnproto/go-capnproto2/issues/418#issuecomment-1375740560_

### PR DESCRIPTION
**Pull request by zenhack**
This fixes #420 (without re-introducing #394, or #349). Per the last commit:

> 420 was a regression introduced by our fix for 394; if we Return()
before we fulfill(), this can result in out of order message delivery,
since incoming calls can be made directly on clients in the result
before all queued calls are drained.
>
> Previously, if we fulfilled() before Return(), we would get a data race
as fillPayloadCapTable modified the message while pipelined calls read
it. Having split Return(error) into PrepareReturn(error) and Return(),
it is now safe to move just the latter after the call to fulfill().

I am now unable to reproduce any of the referenced issues.

### CODE REVIEW

File: capability.go [hunk 1]
```diff
@@ -879,13 +881,21 @@ type Returner interface {
 	// ReleaseResults is called.
 	AllocResults(sz ObjectSize) (Struct, error)
 
-	// Return resolves the method call successfully if e is nil, or failure
-	// otherwise.  Return must be called once.
+	// PrepareReturn finalizes the return message. The method call will
+	// resolve successfully if e is nil, or otherwise it will fail.
```
Comment (lthibault) [inline capability.go:885]: Nit:  I initially misunderstood this to mean "the actual sending of the return message will fail".  Consider updating docstring to something like:

>The method call will resolve successfully if e is nil.  Otherwise, it will return an exception to the caller.

**Review by lthibault — APPROVED** [review]

**Review by lthibault — APPROVED** [review]

**Comment by lthibault** [comment]
```
--- FAIL: TestSendDisembargo (0.01s)
    --- FAIL: TestSendDisembargo/SendQueuedResultToCaller (0.01s)
Error:         level1_test.go:285: Received finish message; want disembargo
Error:         level0_test.go:2126: conn error: rpc: send release: send message: context canceled
```

**Comment by zenhack** [comment]
...that's one of the existing ones.

**Comment by lthibault** [comment]
Yeah, I thought so, but couldn't find an issue for it.  The error in https://github.com/capnproto/go-capnproto2/issues/377 is a different one.

Should I open an issue for this?  (Re-running CI in the meantime.)

**Comment by zenhack** [comment]
Yeah, why don't you open a separate one; I think this one's been around a while but I keep binning it with #377
